trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '12-CI-CD-Pipelines/Azure-Devops/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    backendServiceArm: 'Visual Studio Enterprise – MPN(d3cfc052-05a7-44f5-a6de-33282fe81246)'
    backendAzureRmResourceGroupName: 'CloudSkills'
    backendAzureRmStorageAccountName: 'stcloudskillstfstate'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'tf/terraform.tfstate'
    
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '12-CI-CD-Pipelines/Azure-Devops/AKS'
    commandOptions: '-var="Name=$(Name)" -var="resourceGroup=$(resourceGroup)" -var="clientID=$(clientID)" -var="clientSecret=$(clientSecret)" -var="location=$(location)"'
    environmentServiceNameAzureRM: 'Visual Studio Enterprise – MPN(d3cfc052-05a7-44f5-a6de-33282fe81246)'